add check init validate step

diff --git a/.github/workflows/terraform-workflow.yml b/.github/workflows/terraform-workflow.yml
--- a/.github/workflows/terraform-workflow.yml
+++ b/.github/workflows/terraform-workflow.yml
@@ -72,3 +72,38 @@ jobs:
         run: |
           terraform version
           echo "Terraform version: ${{ env.terraform_version }}"
+      
+      - name: Set job-wide environment variables
+        run: |
+          if [ "${{ inputs.folder }}" == "cloudflare" ]; then
+            echo "TF_VAR_cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
+          fi
+      
+      - name: Init Check Validate Terraform
+        run: |
+          cd "${{ inputs.folder }}"
+          echo "Running terraform init..."
+          terraform init -input=false -upgrade
+
+          if [ $? -ne 0 ]; then
+            echo "Terraform init failed"
+            exit 1
+          fi
+
+          echo "Running terraform format..."
+          terraform fmt -check -diff -recursive
+
+          if [ $? -ne 0 ]; then
+            echo "Terraform format check failed"
+            exit 1
+          fi
+
+          echo "Running terraform validate..."
+          terraform validate
+          if [ $? -ne 0 ]; then
+            echo "Terraform validate failed"
+            exit 1
+          fi
+
+          echo "Terraform init, format, and validate completed successfully."
+
